Accessing parameters for debugging, diagnostics, and visualizations.

Parameter initialization.

Sharing parameters across different model components.

In [1]:
import torch
from torch import nn

net = nn.Sequential(nn.Linear(4,8), nn.ReLU(), nn.Linear(8,1))
X = torch.rand(size=(2,4))
net(X)

tensor([[-0.0580],
        [ 0.0045]], grad_fn=<AddmmBackward>)

### 5.2.1 Parameter Access

In [2]:
# net의 2번째 요소, Linear(8,1)의 state dict
print(net[2].state_dict())

OrderedDict([('weight', tensor([[-0.1843, -0.3107,  0.0330,  0.1771, -0.3446,  0.0716,  0.3247, -0.2141]])), ('bias', tensor([0.0839]))])


### 5.2.1.1 Targeted Parameters

In [5]:
# bias라는 data의 type, class, data 접근

print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

# each parametes의 grad에도 접근 가능!

net[2].weight.grad == None #아직 학습되지 않아서, None(초기화상태)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([0.0839], requires_grad=True)
tensor([0.0839])


True